using AdventOfCode2022Library;

TaskRunner.RunDay("Day1");
TaskRunner.RunDay("Day2");
TaskRunner.RunDay("Day3");
TaskRunner.RunDay("Day4");
TaskRunner.RunDay("Day5");
TaskRunner.RunDay("Day6");
TaskRunner.RunDay("Day7");
TaskRunner.RunDay("Day8");
TaskRunner.RunDay("Day9");
TaskRunner.RunDay("Day10");
TaskRunner.RunDay("Day11");
TaskRunner.RunDay("Day12");
TaskRunner.RunDay("Day13");
TaskRunner.RunDay("Day14");
TaskRunner.RunDay("Day15");
TaskRunner.RunDay("Day16");
TaskRunner.RunDay("Day17");
TaskRunner.RunDay("Day18");
TaskRunner.RunDay("Day19");
TaskRunner.RunDay("Day20");
TaskRunner.RunDay("Day21");
TaskRunner.RunDay("Day22");